<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lagos_cities = [
            'Abule Egba (Agbado Ijaye Road)',
            'Abule Egba (Ajasa Command Rd)',
            'Abule Egba (Ajegunle)',
            'Abule Egba (Alagbado)',
            'Abule Egba (Alakuko)',
            'Abule Egba (Ekoro road)',
            'Abule Egba (Meiran Road)',
            'Abule Egba (New Oko Oba)',
            'Abule Egba (Old Otta Road)',
            'Agbara',
            'Agege (Ajuwon Akute Road)',
            'Agege (Dopemu)',
            'Agege (Iju Road)',
            'Agege (Old Abeokuta Road)',
            'Agege (Old Otta Road)',
            'Agege (Orile Agege)',
            'AGILITI',
            'AGUNGI (LEKKI)',
            'AJAO ESTATE',
            'ALFA BEACH',
            'AMUWO',
            'ANTHONY VILLAGE',
            'Apapa (Ajegunle)',
            'Apapa (Amukoko)',
            'Apapa (GRA)',
            'Apapa (Kiri kiri)',
            'Apapa (Olodi)',
            'Apapa (Suru Alaba)',
            'Apapa (Tincan)',
            'Apapa (Warf Rd)',
            'AWOYAYA',
            'Awoyaya-Container bustop',
            'Awoyaya-Eko Akete Estate',
            'Awoyaya-Eputu',
            'Awoyaya-Gbetu Iwerekun Road',
            'Awoyaya-Idowu Eletu',
            'Awoyaya-Mayfair Gardens',
            'Awoyaya-Ogunlana Busstop',
            'Awoyaya-Ologunfe',
            'Awoyaya-Oribanwa',
            'Badagry',
            'BERGER',
            'Bogije',
            'Coker',
            'Doyin',
            'Ejigbo-Ailegun Road',
            'Ejigbo-Bucknor',
            'Ejigbo-Ile Epo',
            'Ejigbo-Isheri Osun',
            'Ejigbo-Jakande Wood Market',
            'Ejigbo-NNPC Road',
            'Ejigbo-Oke-Afa',
            'Ejigbo-Pipeline',
            'Ejigbo-Powerline',
            'Elemoro',
            'EPE',
            'Fagba (Iju Road)',
            'FESTAC (1st Avenue)',
            'FESTAC (2nd Avenue)',
            'FESTAC (3rd Avenue)',
            'FESTAC (4th Avenue)',
            'FESTAC (5th Avenue)',
            'FESTAC (6th Avenue)',
            'FESTAC (7th Avenue)',
            'Gbagada- Ifako',
            'Gbagada-Abule Okuta',
            'Gbagada-Araromi',
            'Gbagada-Deeper Life',
            'Gbagada-Diya',
            'Gbagada-Expressway',
            'Gbagada-Hospital',
            'Gbagada-L&K',
            'Gbagada-New Garage',
            'Gbagada-Olopomeji',
            'Gbagada-Pedro',
            'Gbagada-Sawmill',
            'Gbagada-Sholuyi',
            'Ibeju Lekki',
            'IDIMU',
            'IGANDO',
            'IJANIKIN',
            'IJEGUN IKOTUN',
            'Ijegun-Obadore Road',
            'IJORA',
            'Ikeja (ADENIYI JONES)',
            'Ikeja (ALAUSA)',
            'Ikeja (ALLEN AVENUE)',
            'Ikeja (computer village)',
            'Ikeja (GRA)',
            'IKEJA (M M Airport)',
            'Ikeja (MANGORO)',
            'Ikeja (OBA-AKRAN)',
            'Ikeja (OPEBI)',
            'IKORODU (Adamo)',
            'IKORODU (Agbede)',
            'Ikorodu (Agbowa)',
            'IKORODU (Agric)',
            'IKORODU (Bayeku)',
            'IKORODU (Eyita)',
            'IKORODU (Gberigbe)',
            'IKORODU (Ijede)',
            'IKORODU (Imota)',
            'IKORODU (Ita oluwo)',
            'IKORODU (Itamaga)',
            'IKORODU (Offin)',
            'IKORODU (Owode-Ibese)',
            'Ikorodu Road-Ajegunle',
            'Ikorodu Road-Irawo',
            'Ikorodu Road-Owode Onirin',
            'IKORODU(Elepe)',
            'IKORODU(Laspotech)',
            'Ikorodu(Ogolonto)',
            'IKORODU(Sabo)',
            'Ikorodu- Imota Caleb University',
            'Ikorodu-Agufoye',
            'Ikorodu-Benson',
            'Ikorodu-Garage',
            'Ikorodu-Odokekere',
            'Ikorodu-Odonla',
            'Ikorodu-Ogijo',
            'IKOTA',
            'IKOTUN',
            'Ikoyi (Awolowo Road)',
            'Ikoyi (Bourdillon)',
            'Ikoyi (Dolphin)',
            'Ikoyi (Glover road)',
            'Ikoyi (Keffi)',
            'Ikoyi (Kings way road)',
            'Ikoyi (Obalende)',
            'Ikoyi (Queens Drive)',
            'IKOYI MTN ( PICKUP STATION)',
            'ILAJE (BARIGA)',
            'ILUPEJU (Lagos)',
            'ISHERI IKOTUN',
            'ISHERI MAGODO',
            'ISOLO',
            'Iyana Ejigbo',
            'IYANA IBA',
            'Iyana Ipaja (Abesan)',
            'Iyana Ipaja (Aboru)',
            'Iyana Ipaja (Ayobo Road)',
            'Iyana Ipaja (Command Road)',
            'Iyana Ipaja (Egbeda)',
            'Iyana Ipaja (Ikola Road)',
            'Iyana Ipaja (Iyana Ipaja Road)',
            'Iyana Ipaja (Shasha)',
            'JAKANDE (LEKKI)',
            'JANKANDE (ISOLO)',
            'Jumia-Experience-Center',
            'Ketu- Agboyi',
            'Ketu-Alapere',
            'Ketu-CMD road',
            'Ketu-Demurin',
            'Ketu-Ikosi Road',
            'Ketu-Ile Ile',
            'Ketu-Iyana School',
            'Ketu-Tipper Garage',
            'Lagos Island (Adeniji)',
            'Lagos Island (Marina)',
            'Lagos Island (Onikan)',
            'Lagos Island (Sura)',
            'Lagos Island (TBS)',
            'LAKOWE',
            'Lakowe-Adeba Road',
            'Lakowe-Golf',
            'Lakowe-Kajola',
            'Lakowe-School Gate',
            'LEKKI -VGC',
            'Lekki 1 (Bishop Durosimi)',
            'Lekki 1 (F.T Kuboye street)',
            'Lekki 1 (Omorinre Johnson)',
            'Lekki Phase 1 (Admiralty Road)',
            'Lekki Phase 1 (Admiralty way)',
            'Lekki Phase 1 (Fola Osibo)',
            'LEKKI-AGUNGI',
            'LEKKI-AJAH (ABIJO)',
            'LEKKI-AJAH (ADDO ROAD)',
            'LEKKI-AJAH (BADORE)',
            'LEKKI-AJAH (ILAJE)',
            'LEKKI-AJAH (ILASAN)',
            'LEKKI-AJAH (JAKANDE)',
            'LEKKI-AJAH (SANGOTEDO)',
            'Lekki-Awoyaya',
            'Lekki-Chisco',
            'LEKKI-ELF',
            'LEKKI-IGBOEFON',
            'LEKKI-IKATE ELEGUSHI',
            'LEKKI-JAKANDE (KAZEEM ELETU)',
            'LEKKI-MARUWA',
            'LEKKI-ONIRU ESTATE',
            'LEKKI-OSAPA LONDON',
            'Magboro',
            'MAGODO',
            'MARYLAND (MENDE)',
            'MARYLAND (ONIGBONGBO)',
            'MEBANMU',
            'MILE 12',
            'Mile 12 -Ajelogo',
            'Mile 12-Agboyi Ketu',
            'Mile 12-Doyin Omololu',
            'Mile 12-Orishigun',
            'MILE 2',
            'Mushin -Palm Avenue',
            'Mushin-Agege Motor Road',
            'Mushin-Daleko Market',
            'Mushin-Fatai Atere',
            'Mushin-Idi Oro',
            'Mushin-Idi-Araba',
            'Mushin-Ilasamaja Road',
            'Mushin-Isolo Road',
            'Mushin-Ladipo Road',
            'Mushin-Mushin Market',
            'Mushin-Olateju',
            'Mushin-Papa Ajao',
            'Odongunyan',
            'Ogba- Akilo Road',
            'Ogba- College Road',
            'Ogba- Lateef Jakande Road',
            'Ogba-Acme Road',
            'Ogba-Aguda',
            'Ogba-County',
            'Ogba-Ifako-Idiagbon',
            'Ogba-Ifako-Orimolade',
            'Ogba-Isheri Road',
            'Ogba-Obawole',
            'Ogba-Ojodu',
            'Ogba-Oke Ira',
            'Ogba-Oke Ira 2nd Juction',
            'OGBA-Surulere Ind Rd',
            'Ogba-Wemco Road',
            'OGUDU',
            'OJO',
            'Ojo Shibiri',
            'Ojo-Abule Oshun',
            'Ojo-Adaloko',
            'Ojo-Agric',
            'Ojo-Ajangbadi',
            'Ojo-Alaba International',
            'Ojo-Alaba Rago',
            'Ojo-Alaba Suru',
            'Ojo-Alakija',
            'Ojo-Cassidy',
            'Ojo-Ijegun',
            'Ojo-Ilogbo',
            'Ojo-Ojo Barracks',
            'Ojo-Okokomaiko',
            'Ojo-Old Ojo road',
            'Ojo-Onireke',
            'Ojo-PPL',
            'Ojo-Shibiri',
            'Ojo-Tedi Town',
            'Ojo-Trade Fair',
            'Ojo-Volks',
            'OJODU',
            'OJOKORO',
            'OJOTA',
            'OKOKOMAIKO',
            'OKOTA',
            'Omole Phase 1',
            'Omole Phase 2',
            'OREGUN',
            'Oreyo- Igbe',
            'ORILE',
            'OSAPA (LEKKI)',
            'OSHODI-BOLADE',
            'OSHODI-ISOLO',
            'OSHODI-MAFOLUKU',
            'OSHODI-ORILE',
            'OSHODI-SHOGUNLE',
            'Palmgrove-Onipanu',
            'Sari-Iganmu',
            'Satelite-Town',
            'SOMOLU',
            'Surulere (Adeniran Ogunsanya)',
            'Surulere (Aguda)',
            'Surulere (Bode Thomas)',
            'Surulere (Fatia Shitta)',
            'Surulere (Idi Araba)',
            'Surulere (Ijesha)',
            'Surulere (Iponri)',
            'Surulere (Itire)',
            'Surulere (Lawanson)',
            'Surulere (Masha)',
            'Surulere (Ogunlana drive)',
            'Surulere (Ojuelegba)',
            'VI (Adetokunbo Ademola)',
            'VI (Ahmed Bello way)',
            'VI (Bishop Aboyade Cole)',
            'VI(Ajose Adeogun)',
            'VI(Akin Adeshola)',
            'VI(Bishop Oluwale)',
            'VI(Yusuf Abiodun)',
            'Victoria Island (Adeola Odeku)',
            'Victoria Island (Kofo Abayomi)',
            'Yaba- Abule Ijesha',
            'Yaba- Fadeyi',
            'Yaba-(Sabo)',
            'Yaba-(Unilag)',
            'Yaba-Abule Oja',
            'Yaba-Adekunle',
            'Yaba-Akoka',
            'Yaba-Alagomeju',
            'Yaba-College of Education',
            'Yaba-Commercial Avenue',
            'Yaba-Folagoro',
            'Yaba-Herbert Macaulay Way',
            'Yaba-Jibowu',
            'Yaba-Makoko',
            'Yaba-Murtala Muhammed Way',
            'Yaba-Onike Iwaya',
            'Yaba-Oyingbo',
            'Yaba-Tejuosho',
            'Yaba-University Road',
            'Yaba-Yabatech',
        ];

        $abuja_cities = [
            'ABAJI',
            'ABUJA AIRPORT ROAD- ABUJA TECHNOLOGY VILLAGE',
            'ABUJA AIRPORT ROAD- CHIKA',
            'ABUJA AIRPORT ROAD- GOSA / SABON LUGBE',
            'ABUJA AIRPORT ROAD- KUCHINGORO',
            'ABUJA AIRPORT ROAD- KYAMI / CENTENARY CITY',
            'ABUJA AIRPORT ROAD- NNAMDI AZIKE AIRPORT',
            'ABUJA AIRPORT ROAD- PIWOYI',
            'ABUJA AIRPORT ROAD- PYAKASA',
            'ABUJA AIRPORT ROAD- RIVERPARK /TRADEMORE',
            'ABUJA AIRPORT ROAD- SAUKA/IMMIGRATION HQ',
            'ABUJA- APO CENTRAL',
            'ABUJA- APO LEGISLATIVE ZONE A',
            'ABUJA- APO LEGISLATIVE ZONE B',
            'ABUJA- APO LEGISLATIVE ZONE C',
            'ABUJA- APO LEGISLATIVE ZONE D',
            'ABUJA- APO LEGISLATIVE ZONE E',
            'ABUJA- APO MECHANIC VILLAGE',
            'ABUJA- APO RESETTLEMENT ZONE A',
            'ABUJA- APO RESETTLEMENT ZONE B',
            'ABUJA- APO RESETTLEMENT ZONE C',
            'ABUJA- APO RESETTLEMENT ZONE D',
            'ABUJA- APO RESETTLEMENT ZONE E',
            'ABUJA- DURUMI',
            'ABUJA- DURUMI PHASE 2',
            'ABUJA- GARKI AREA 1',
            'ABUJA- GARKI AREA 10',
            'ABUJA- GARKI AREA 11',
            'ABUJA- GARKI AREA 2',
            'ABUJA- GARKI AREA 3',
            'ABUJA- GARKI AREA 7',
            'ABUJA- GARKI AREA 8',
            'ABUJA- GWARINPA 1ST AVENUE',
            'ABUJA- GWARINPA 2ND AVENUE',
            'ABUJA- GWARINPA 3RD AVENUE',
            'ABUJA- GWARINPA 4TH AVENUE',
            'ABUJA- GWARINPA 5TH AVENUE',
            'ABUJA- GWARINPA 6TH AVENUE',
            'ABUJA- GWARINPA 7TH AVENUE',
            'ABUJA- GWARINPA EXTENSION',
            'ABUJA- KATAMPE EXTENSION',
            'ABUJA- KATAMPE MAIN',
            'ABUJA- KUBWA 2/1 PHASE 1',
            'ABUJA- KUBWA 2/2 PHASE 2',
            'ABUJA- KUBWA ARAB ROAD',
            'ABUJA- KUBWA BYAZHIN',
            'ABUJA- KUBWA EXTENSION 3',
            'ABUJA- KUBWA GBAZANGO',
            'ABUJA- KUBWA PHASE 3',
            'ABUJA- KUBWA PW',
            'ABUJA- KUBWA- FCDA/FHA',
            'ABUJA- LIFE CAMP EXTENSION',
            'ABUJA- MABUSHI',
            'ABUJA- MAITAMA ALEIRO',
            'ABUJA- MAITAMA ASO DRIVE',
            'ABUJA- MAITAMA CENTRAL',
            'ABUJA- MAITAMA EXTENSION',
            'ABUJA-ASOKORO',
            'ABUJA-BWARI',
            'Abuja-Central',
            'Abuja-Dakibiyu',
            'ABUJA-DAWAKI',
            'ABUJA-DEI-DEI',
            'ABUJA-DUTSE',
            'ABUJA-EFAB',
            'ABUJA-GALADIMAWA',
            'ABUJA-GAMES VILLAGE',
            'ABUJA-GARKI2',
            'ABUJA-GUDU',
            'ABUJA-GUZAPE',
            'ABUJA-GWAGWALADA',
            'ABUJA-JABI',
            'ABUJA-JAHI',
            'ABUJA-KABUSA',
            'ABUJA-KADO',
            'ABUJA-KARU',
            'ABUJA-KAURA DISTRICT',
            'ABUJA-KUJE',
            'ABUJA-LIFE CAMP',
            'ABUJA-LOKOGOMA',
            'Abuja-Lugbe Across Zone1-9',
            'Abuja-Lugbe Kapwa',
            'Abuja-Lugbe MrBiggs',
            'Abuja-Lugbe New Site',
            'Abuja-Lugbe Peace Village',
            'Abuja-Lugbe Police Sign Post',
            'Abuja-Lugbe Premier Academy',
            'Abuja-Lugbe Sector F',
            'Abuja-Lugbe Skye Bank',
            'Abuja-Lugbe Total',
            'Abuja-Lugbe Tudun Wada',
            'ABUJA-MARARABA',
            'ABUJA-NYANYA',
            'Abuja-Prince and Princess',
            'ABUJA-SUNCITY',
            'ABUJA-SUNNY VALLE',
            'ABUJA-UTAKO',
            'ABUJA-WUSE ZONE 1',
            'ABUJA-WUSE ZONE 2',
            'ABUJA-WUSE ZONE 3',
            'ABUJA-WUSE ZONE 4',
            'ABUJA-WUSE ZONE 5',
            'ABUJA-WUSE ZONE 6',
            'ABUJA-WUSE ZONE 7',
            'ABUJA-WUSE11',
            'Abuja-Wuye',
            'Airport Road Iddo',
            'Airport Road Kuchingoro / Chika / Pyakasa',
            'Airport Road Sauka /Trademore / Airport',
            'Dutse',
            'GIDAN MANGORO',
            'GWAGWALADA',
            'IDU',
            'Jikowyi',
            'Karimo',
            'KARU',
            'Kubwa Central',
            'KWALI',
            'Lugbe',
            'MINISTERS HILL',
            'Mpape',
            'NICON JUNCTION',
            'Tungan Maje',
            'Zuba',
        ];

        $rivers_cities = [
            'ABHONEMA',
            'AHOADA',
            'AIRPORT ROAD - PORT HARCOURT',
            'Bonny Island',
            'ELELE',
            'Elelewon',
            'ELEME-AGBONCHIA',
            'ELEME-AKPAJO',
            'ELEME-ALESA',
            'ELEME-ALETO',
            'ELEME-ALODE',
            'ELEME-EBUBU',
            'ELEME-EKPORO',
            'ELEME-ETEO',
            'ELEME-NCHIA',
            'ELEME-ODIDO',
            'ELEME-OGALE',
            'ELEME-ONNE',
            'EMOUHA',
            'ETCHE',
            'ISIOKPO',
            'Okrika',
            'OKRIKA-OKRIKA TOWN(KIRIKE)',
            'OMOKU',
            'OYIGBO-AFAM',
            'OYIGBO-EGBERU',
            'OYIGBO-IZUOMA',
            'OYIGBO-KOMKOM',
            'OYIGBO-MIRINWANYI',
            'OYIGBO-NDOKI',
            'OYIGBO-OBEAMA',
            'OYIGBO-UMUAGBAI',
            'PHC-NEW GRA -PHASE 1 2 3 4',
            'PHC-RIVER STATE UNIVERSITY',
            'PHC-WOJI Central Location',
            'PORTHARCOURT-ABONNEMA TOWN',
            'PORTHARCOURT-ABONNEMA WHARF',
            'PORTHARCOURT-ABULOMA',
            'PORTHARCOURT-ADA GEORGE',
            'PORTHARCOURT-AGIP',
            'PORTHARCOURT-AIRFORCE BASE',
            'PORTHARCOURT-AKPAJO',
            'PORTHARCOURT-ALAKAHIA-UPTH',
            'PORTHARCOURT-ALUU',
            'PORTHARCOURT-AMADI AMA',
            'PORTHARCOURT-AYA-OGOLOGO',
            'PORTHARCOURT-AZUBIE',
            'PORTHARCOURT-BORI CAMP',
            'PORTHARCOURT-BOROKIRI',
            'PORTHARCOURT-CHOBA',
            'PORTHARCOURT-CHOBA-UNIPORT',
            'PORTHARCOURT-CHURCHHILL',
            'PORTHARCOURT-D/LINE',
            'PORTHARCOURT-DARICK POLO',
            'PORTHARCOURT-DIOBU',
            'PORTHARCOURT-EAGLE ISLAND',
            'PORTHARCOURT-EGBELU',
            'PORTHARCOURT-ELEKAHIA',
            'PORTHARCOURT-ELELEWON',
            'PORTHARCOURT-ELIBOLO',
            'PORTHARCOURT-ELIGBAM',
            'PORTHARCOURT-ELIMGBU',
            'PORTHARCOURT-ELINPARAWON',
            'PORTHARCOURT-ELIOHANI',
            'PORTHARCOURT-ELIOZU',
            'PORTHARCOURT-ENEKA',
            'PORTHARCOURT-IGWURUTA',
            'PORTHARCOURT-INTELS KM 16',
            'PORTHARCOURT-MGBUOBA',
            'PORTHARCOURT-MILE 1',
            'PORTHARCOURT-MILE 2',
            'PORTHARCOURT-MILE 3',
            'PORTHARCOURT-MILE 4',
            'PORTHARCOURT-MILE 5',
            'PORTHARCOURT-MUGBUOSIMINI',
            'PORTHARCOURT-NEW GRA-TOMBIA',
            'PORTHARCOURT-NKPOGU',
            'PORTHARCOURT-NKPOLU',
            'PORTHARCOURT-OGBATAI',
            'PORTHARCOURT-OGBOGORO',
            'PORTHARCOURT-OGBUNABALI',
            'PORTHARCOURT-OGINIGBA',
            'PORTHARCOURT-OKPORO ROAD',
            'PORTHARCOURT-OKURU',
            'PORTHARCOURT-OLD GRA',
            'PORTHARCOURT-ORAZI',
            'PORTHARCOURT-OZUBOKO',
            'PORTHARCOURT-PETER ODILLI ROAD',
            'PORTHARCOURT-RECLAMATION',
            'PORTHARCOURT-RUKPOKWU',
            'PORTHARCOURT-RUMEME',
            'PORTHARCOURT-RUMUAGHAOLU',
            'PORTHARCOURT-RUMUAKPAKOLOSI',
            'PORTHARCOURT-RUMUEPIRIKOM',
            'PORTHARCOURT-RUMUEVOLU',
            'PORTHARCOURT-RUMUIBEKWE',
            'PORTHARCOURT-RUMUIGBO',
            'PORTHARCOURT-RUMUKALAGBOR',
            'PORTHARCOURT-RUMUKRUSHI',
            'PORTHARCOURT-RUMUMASI',
            'PORTHARCOURT-RUMUODUMAYA',
            'PORTHARCOURT-RUMUOGBA',
            'PORTHARCOURT-RUMUOKE',
            'PORTHARCOURT-RUMUOKORO',
            'PORTHARCOURT-RUMUOKWUTA',
            'PORTHARCOURT-RUMUOLA',
            'PORTHARCOURT-RUMUOLUMENI',
            'PORTHARCOURT-RUMUOROSI',
            'PORTHARCOURT-RUMUOWAH',
            'PORTHARCOURT-STADIUM ROAD',
            'PORTHARCOURT-TOWN',
            'PORTHARCOURT-TRANS AMADI',
            'PORTHARCOURT-WOJI ILLOM',
            'PORTHARCOURT-WOJI ROAD',
            'PORTHARCOURT-WOJI YKC',
            'PORTHARCOURT-WOJI-ELIJIJI',
            'RUMUAGHOLU',
            'RUMUODUOMAYA',
        ];

        foreach ($lagos_cities as $key => $city) {
            $model = new City();
            $model->name = $city;
            $model->state_id = 25;
            $model->save();
        }

        foreach ($abuja_cities as $key => $city) {
            $model = new City();
            $model->name = $city;
            $model->state_id = 15;
            $model->save();
        }

        foreach ($rivers_cities as $key => $city) {
            $model = new City();
            $model->name = $city;
            $model->state_id = 33;
            $model->save();
        }
    }
}
